### ISSUE TITLE
If you don't mind a partner for this project...

### ISSUE THREAD

**Issue by ProLoser** [iamawong-zz/cards-against-humanity#12]
If you don't mind someone collaborating with you on this project, I don't mind working on the frontend if you're able to focus on the backend? I'm semi-savi on node but I code FE like a pro.

**Comment by iamawong-zz** [comment]
What's your google?

**Comment by iamawong-zz** [comment]
Just message me on gchat/AIM: sn is th5418

Date: Sun, 21 Oct 2012 21:43:44 -0700
